config/routes.rb
Lendmeyourhand::Application.routes.draw do
  root :to => 'hands#welcome'

  resources :hands do
    member do 
      post 'guess'
    end
  end
  
  match '/random', :to => 'hands#random', :as => 'random'

end

app/models/hand.rb
class Hand < ActiveRecord::Base
  include Paperclip::Glue

  has_attached_file :picture, 
    :styles => {:large => '600x600>', 
                :medium => "300x300>", 
                :thumb => "100x100>" },
    :storage => :s3,
    :s3_credentials => {:access_key_id     => ENV['S3_KEY'],
                        :secret_access_key => ENV['S3_SECRET']},
    :path => ":sytle/:id/:filename.:extension",
    :bucket => 'lendmeyourhand'  


  validates_presence_of :name
  validates_attachment_presence :picture
  #validates_attachment_size :picture, :less_than => 2.megabyte

  attr_accessor :guess
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hands_controller.rb
class HandsController < ApplicationController
  # GET /hands
  # GET /hands.json

  def welcome

  end

  def random
    id = rand(Hand.count)
    id = id + 1 if id == 0
    redirect_to :action => 'show', :id => id
  end

  def index
    @hands = Hand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hands }
    end
  end

  # GET /hands/1
  # GET /hands/1.json
  def show
    @hand = Hand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hand }
    end
  end

  # GET /hands/new
  # GET /hands/new.json
  def new
    @hand = Hand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hand }
    end
  end

  # GET /hands/1/edit
  def edit
    @hand = Hand.find(params[:id])
  end

  # POST /hands
  # POST /hands.json
  def create
    @hand = Hand.new(params[:hand])

    respond_to do |format|
      if @hand.save
        format.html { redirect_to @hand, notice: 'Hand was successfully created.' }
        format.json { render json: @hand, status: :created, location: @hand }
      else
        format.html { render action: "new" }
        format.json { render json: @hand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hands/1
  # PUT /hands/1.json
  def update
    @hand = Hand.find(params[:id])

    respond_to do |format|
      if @hand.update_attributes(params[:hand])
        format.html { redirect_to @hand, notice: 'Hand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hands/1
  # DELETE /hands/1.json
  def destroy
    @hand = Hand.find(params[:id])
    @hand.destroy

    respond_to do |format|
      format.html { redirect_to hands_url }
      format.json { head :no_content }
    end
  end

  def guess
    @hand = Hand.find(params[:id])
    @guess = params[:guess][:guess]

    if @hand.name.downcase.strip.include?(@guess.downcase.strip)
      @hand.update_attributes(:count => @hand.count.to_i + 1)
      flash[:notice] = "You got it right that was #{@hand.name}'s hand. 
      This hand has been guessed correctly #{@hand.count} times!  Now guess another."
    else
      flash[:error] = "NOPE that was #{@hand.name}'s hand."
    end
      redirect_to :action => 'index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hands_helper.rb
module HandsHelper
end

app/views/hands/_form.html.erb
<%= form_for @hand, :html => { :class => 'form-horizontal', :multipart => true} do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Hand</legend>
    <p>    
      When uploading a hand please try to use a white background or something that is non distintive in the picture
    dont make it too easy!
    </p>
    <br />
    <br />

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :photo, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :picture, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', hands_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/hands/edit.html.erb
<%= render :partial => 'form' %>

app/views/hands/index.html.erb
<h1>Hands</h1>
<%= button_to 'Guess a random hand', '/random', :class => 'btn btn-danger', :method => 'get' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @hands.each do |hand| %>
      <tr>
        <td><%= link_to image_tag(hand.picture.url(:thumb)), hand_path(hand) %></td>
        <td>
          <%= link_to 'Guess', hand_path(hand), :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Lend a hand', new_hand_path, :class => 'btn btn-primary' %>

app/views/hands/new.html.erb
<%= render :partial => 'form' %>

app/views/hands/show.html.erb
<h1>Hand</h1>
<%= button_to 'Guess a another random hand', '/random', :class => 'btn btn-danger', :method => 'get' %>

<%= form_for :guess, :url => {:controller => 'hands', :action => 'guess', :id => @hand.id}, :html => { :class => 'form-horizontal'} do |f| -%>
  <fieldset>
    <legend>Whos Hand is This?</legend>

    <div class="control-group">
      <%= f.label :guess, "Make your guess", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :guess, :class => 'text_field' %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit 'Guess', :class => 'btn btn-primary' %>
    </div>

  </fieldset>
<% end -%>

<p>
  <b>Photo</b><br>
  <%= image_tag @hand.picture.url(:large) %>
</p>




<div class="form-actions">
  <%= link_to 'Want to edit this hand?', edit_hand_path(@hand), :class => 'btn' %>
</div>

app/views/hands/welcome.html.erb
<div class="container">
  <div class="content">
    <div class="row">
      <div class="span12">
        <h3>Why?</h3>
        <p> 
        Christie's mock trial has a section in which the parents of the murder victim are able to identify the deceased solely on the severed hand of the deceased.</p>
        </p>
        <p>
        I called bullshit and said no one can identify someone just based on their hand (including myself), Christie disagrees.
        </p>
        <h4>The question is could you truthfully and accurately identify someone by only looking at their hand? </h4>
        <br />
        <br />
        <br />

        <%= button_to 'Well GET GUESSING', '/hands', :class => 'btn btn-danger', :method => 'get' %>
        </p>              
      </div><!--/span-->
    </div><!--/row-->
  </div><!--/content-->
</div> <!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lend Me Your Hand</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Lend Me Your Hand</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Guess Hands", "/hands"  %></li>
              <li><%= link_to "Lend a hand", :controller => 'hands', :action => 'new'  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <% flash.each do |key, value| %>
        <div class="alert alert-block alert-<%= key == :notice ? "success" : key %>" data-dismiss="alert">
          <a class="close">×</a>
          <h4 class="alert-heading"><%= key.capitalize %>:</h4>
          <%= value %>
        </div>
    <% end %>


    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
           </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>